" ##############
" Bryley's vimrc
" ##############

" ### Basic must have settings ###
syntax enable						" Enable Syntax
set number relativenumber			" Haves relative line numbers on the side of the screen in hybrid mode
filetype indent on					" Will enable automatic indentation detection based on the filetype
set lazyredraw						" Will stop redrawing the screen in times it doesn't need to like macros
set showmatch						" Will show matching parenthesises when hovering over one.
"match Error /\%81v.\+/				" Highlights characters over 80 columns long
set colorcolumn=80
set spelllang=en_au					" Sets spelling to Australian spelling.
set mouse=a							" Enables mouse
set splitbelow						" Makes vim automatically open new split windows below instead of above
set splitright						" Makes vim automatically open new vsplit windows to the right instead of left
set termguicolors					" Enables all colors.

" Tabs
set cindent
set noexpandtab
set tabstop=4
set shiftwidth=4

" Change the leader to space by remapping it then changing it
nnoremap <SPACE> <Nop>
let mapleader=" "


" ### Fuzzy finder settings ###
set wildignore+=node_modules/*		" Will ignore node_modules folder when searching
set path+=**						" When searching for files it will check subfolders
set wildmenu						" Will show a box of different suggestions when typing commands

" ### Plugins ###
call plug#begin('~/.config/nvim/plugged')

Plug 'Mofiqul/vscode.nvim'			" The VS Code like theme
" Note that this plugin only works for version 0.5 and to change the branch
" when 0.6 comes out:
Plug 'nvim-treesitter/nvim-treesitter', {'branch': '0.5-compat'} " This is used for code parsing and better syntax highlighting, note this should be included in neovim 0.6
Plug 'neovim/nvim-lspconfig'		" Used for autocompleting and reference finding
Plug 'williamboman/nvim-lsp-installer' " This is an easy Language Server installer for lspconfig
Plug 'L3MON4D3/LuaSnip'				" Snippets plugin
Plug 'onsails/lspkind-nvim'			" Adds icons to autocomplete menu
"Plug 'antoinemadec/FixCursorHold.nvim' " Used to fix issues with lspsaga

" nvim-cmp plugins
Plug 'hrsh7th/nvim-cmp'				" Base code for autocompleting
Plug 'hrsh7th/cmp-nvim-lsp'			" Used for LSP autocomplete
Plug 'hrsh7th/cmp-buffer'			" Autocompleting within buffer
Plug 'hrsh7th/cmp-path'				" Autocompleting paths
Plug 'hrsh7th/cmp-cmdline'			" Autocomplete vim commands
Plug 'hrsh7th/cmp-nvim-lua'			" Autocompleting neovim lua code
Plug 'saadparwaiz1/cmp_luasnip'		" Lets cmp work with LuaSnip plugin

"Plug 'glepnir/lspsaga.nvim'			" Creates better dropdown menus with LSP
Plug 'psliwka/vim-smoothie'			" Used for smooth scrolling when using Ctrl-D and Ctrl-U
Plug 'kshenoy/vim-signature' 		" A simple plugin for displaying markers
"Plug 'preservim/nerdtree'			" A sidebar file navagator (Shortcut set to F2)
Plug 'kyazdani42/nvim-tree.lua'		" A sidebar file navigation plugin like NERDTree
Plug 'nvim-lualine/lualine.nvim'	" Fancy bottom bar
Plug 'kyazdani42/nvim-web-devicons' " Adds icons to NerdTree and other plugins
"Plug 'romgrk/barbar.nvim'			" Adds fancy new tabs like VS Code

call plug#end()

let g:vscode_style = "dark"
try
    colorscheme vscode
catch
endtry

" ### Dracula Colorscheme theme ###
" let g:dracula_italic = 0 " Fixes issue with random types highlighting randomly
" packadd! dracula
" colorscheme dracula
" Allows the colorscheme to have a transparent background
" hi Normal guibg=NONE ctermbg=NONE

" ### Autocmd commands ###
" Turn off the error matching for markdown files.
autocmd BufNewFile,BufRead *.md match none
" Enable spelling by default for markdown files.
autocmd BufNewFile,BufRead *.md set spell

" Line numbers for NerdTree
" enable line numbers
let NERDTreeShowLineNumbers=1
" make sure relative line numbers are used
autocmd FileType nerdtree setlocal relativenumber


" ### Mappings ###
" Makes control-backspace delete a word
imap <C-H> <C-W>
" Toggles spelling
nnoremap <leader>s :set spell!<CR>

nnoremap <F2> :NvimTreeToggle<CR>
nnoremap <F3> :noh<CR>
nnoremap <F5> :15split<CR>:term python3 %<CR>

" This is essential for 'vim which key' plugin
" TODO this not working correctly
set notimeout
nnoremap <silent> <leader> :WhichKey '<Space>'<CR>
